#client listener
listenip=0.0.0.0
listenport=20000

#server listener
serverip=127.0.0.1
serverport=8000

logfiledir=logs/
logfilename=chatserver
logbinarypackage=0

#mysql config
dbserver=127.0.0.1
dbuser=root
dbpassword=123456
dbname=chat